name: AutoUpdate

on:
  schedule:
    - cron: '0 4 * * *'

defaults:
  run:
    shell: pwsh

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.5
    - name: Update
      env:
        AZ_AUTH_TOKEN: ${{ secrets.AZ_TOKEN }}
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
      run: ./build.ps1 -t autoupdate